# Generated by Django 5.2.3 on 2025-06-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='todos',
            unique_together=set(),
        ),
    ]
